apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-vare-app
  namespace: vare-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dp-vare-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 10
          type: Utilization
