kind: Service
apiVersion: v1
metadata:
  name: vare-app
  namespace: ww-test
spec:
  ports:
    - name: 5000-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: vare-app
    deployment: vare-app

